# Generated by Django 5.1.5 on 2025-01-21 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sercretId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
