# Generated by Django 5.1.5 on 2025-01-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sercretId',
            new_name='secretId',
        ),
    ]
