# Generated by Django 5.1.5 on 2025-01-26 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_rename_sercretid_customuser_secretid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('fb_link', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Podcasts', 'Podcasts'), ('Educational', 'Educational'), ('Music', 'Music'), ('Gaming', 'Gaming'), ('Vlogs', 'Vlogs'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Fitness', 'Fitness'), ('Food & Cooking', 'Food & Cooking'), ('Beauty & Fashion', 'Beauty & Fashion'), ('Comedy', 'Comedy'), ('DIY & Crafts', 'DIY & Crafts'), ('Reviews & Unboxing', 'Reviews & Unboxing'), ('Motivational', 'Motivational'), ('Science & Experiments', 'Science & Experiments'), ('News & Politics', 'News & Politics'), ('Sports', 'Sports'), ('Animation', 'Animation'), ('Documentary', 'Documentary'), ('History', 'History'), ('Art & Design', 'Art & Design'), ('Business & Finance', 'Business & Finance'), ('Health & Wellness', 'Health & Wellness'), ('Parenting', 'Parenting'), ('ASMR', 'ASMR'), ('Short Films', 'Short Films'), ('Spirituality', 'Spirituality'), ('Wildlife & Nature', 'Wildlife & Nature'), ('Tutorials', 'Tutorials')], max_length=21)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
