# Generated by Django 5.1.5 on 2025-01-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_creatorchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorchannel',
            name='picture',
            field=models.ImageField(default='channel_pics/default_creator.jpg', upload_to=''),
        ),
    ]
