# Generated by Django 5.1.5 on 2025-01-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_creatorchannel_picture'),
        ('videos', '0003_video_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='history',
            field=models.ManyToManyField(related_name='watched_by', to='videos.video'),
        ),
    ]
